### ISSUE TITLE
JTAC - Predator UAV 

### ISSUE THREAD

**Issue by FooxLee** [ciribob/DCS-CTLD#104]
Dear friends, looking at the development of technology in the military industry, please help me to
make an unmanned aerial vehicle as JTAC in this script, the unit of military equipment JTAC make Predator UAV.
Tried modifying the script, cargo - Predator UAV spun up, but does not deploy to the battlefield =(
Ideally, with the ability to add or disable the parameter - invisibility to the enemy.
Thank you ! =)

`ctld.jtacUnitTypes = {
"SKP", "RQ"
}

{ weight = 520, desc = "Predator UAV - JTAC", unit = "RQ_1A_Predator", side = 2 }, `

**Comment by JTFMoney** [comment]
FooxLee, the instructions to make a Predator UAV a JTAC is in the script itself. You can add it to a mission by adding the mist script and the ctld script individually as a doscriptfile in the mission editor and then adding a doscript as "ctld.JTACAutoLase('Colt 11 AFAC', 1688)" no parenthesis...Unit name must be the Colt 11 AFAC and task as recon. It will lase on code 1688.
