### ISSUE TITLE
Sound for script actions

### ISSUE THREAD

**Issue by FooxLee** [ciribob/DCS-CTLD#105]
Gentlemen, I sincerely declare that your script is great!
Could you please tell me how to add sound to actions, for example, loading/unloading infantry,
EXAMPLE: Troops are loaded into the chopper - beep beep .
Paratroopers unloading - beep =)
All the head broke, can not figure it out =( can share a fragment of the script, where it is implemented =) thanks

**Comment by davidp57** [comment]
That's not an issue; you can go ask your question on [Ciribob's Discord](https://discord.com/channels/298054423656005632/860859100056256523)
