### ISSUE TITLE
unit identifier

### ISSUE THREAD

**Issue by FooxLee** [ciribob/DCS-CTLD#106]
friends, where can I see the unit indicators? 
example :
САУ 2С19 Msta - "SAU Msta" , Миномет 2B11 - "2B11 mortar" etc.

**Comment by davidp57** [comment]
Hi,

I don't understand the question.

If you're talking about having a list of units in DCS, you can use [this script](https://github.com/VEAF/VEAF-Mission-Creation-Tools/blob/master/src/scripts/veaf/dcsDataExport.lua) from the VEAF MCT
