### ISSUE TITLE
How do I destroy a crate that was created because of a wrong choice?

### ISSUE THREAD

**Issue by HappyVoo** [ciribob/DCS-CTLD#112]

**Comment by atcz** [comment]
You can load the crate, climb above 40 meters and drop it, it will be destroyed.  There probably could be a "Destroy Nearest Crate" option in the menu.  Dropping it from 40m seems to be an OK alternative.

**Comment by davidp57** [comment]
There is no specific way of doing this.
As @atcz said, you can drop it from high enough. You can use other means of destroying items in DCS (the [VEAF MCT](https://github.com/VEAF/VEAF-Mission-Creation-Tools) scripts, the [Olympus](https://github.com/Pax1601/DCSOlympus) tool, a [big enough explosion](https://en.wikipedia.org/wiki/GBU-43/B_MOAB#:~:text=The%20GBU%2D43%2FB%20Massive,was%20first%20tested%20in%202003.)).
