### ISSUE TITLE
Turned on Sling Mode, No crashes, but once load is dropped it will not let you select another load (log attached)

### ISSUE THREAD

**Issue by afinegan** [ciribob/DCS-CTLD#23]
Turned on Sling Mode(and static bug false), Server Has Not Crashed once (I crashed the copter carrying things many times), but once load is dropped it will not let you select another load (log attached and lua file). it gives you the menu to cancel the request and it wont let you cancel the request either.
[dcs.zip](https://github.com/ciribob/DCS-CTLD/files/380529/dcs.zip)
[CTLD_Drex.zip](https://github.com/ciribob/DCS-CTLD/files/380530/CTLD_Drex.zip)

**Comment by ciribob** [comment]
is this on Nevada or Caucasus?

I'm going to do a release on Sunday that will properly destroy a sling loaded crate once unpacked which should fix the issue on Caucasus. On Nevada it won't work until its patched with all the 1.5 fixes but that should be soon :)

Sorry for the trouble!

**Comment by afinegan** [comment]
This is on the Caucasus map

No trouble, I code for a living, wish I had the time to help you with it and put in a pull request!

**Comment by ciribob** [comment]
OK investigated. This is a bug in Caucasus but not present in the DCS tester version so it's already fixed internally.

New version i just pushed works around it by destroying the crate when unpacked but you always have to unpack the crate which makes multi-crates builds impossible.... Hopefully should be pushed live in the next update. Will try to test in current Nevada build as well
