### ISSUE TITLE
Spawn a new crate of the same weight as the old one, the old one dissappears

### ISSUE THREAD

**Issue by afinegan** [ciribob/DCS-CTLD#26]
Spawn a new crate of the same weight as the old one, the old one dissappears, different weights stick around, but same weight, the old one dissappears, I think this started right around when 1.5.5 came out 2 patches ago

**Comment by ciribob** [comment]
is this only for real sling load crates or the simulated ones as well?

Thanks for the report

**Comment by afinegan** [comment]
Real sling loaded crates, I found the issue, mist.getNextUnitId() (for _unitId) keeps giving me a value of 140000 over and over again, for now I tried a dirty workaround, math.random(100000000,200000000) and it spawned new crates

**Comment by ciribob** [comment]
Well that's odd. 

What version of mist?

Afaik the mist function is literally just add one and return


I'll patch round away today and start 100,000 higher or something

Thanks for solving it as well :)

**Comment by afinegan** [comment]
Mist is version 4.3.73 , yes it is pretty odd, I prob should of looked into it more, but have been running with my head cutt off like usual (short on time lol)

**Comment by ciribob** [comment]
Should be fixed in the new release 👍
