### ISSUE TITLE
Crashes when using spawnGroupAtTrigger

### ISSUE THREAD

**Issue by emilianomolina** [ciribob/DCS-CTLD#27]
This is a weird one and may not be an issue with CTLD at all.

I am using spawnGroupAtTrigger to create a group at a location a few miles away from the player helicopter.

The group is created, and the payer can fly to it just fine, BUT, if the radio menu is bought up when within a few hundred meters of the created group, DCS crashes.  Not always, but very often.

When I say radio menu, I don't mean just the CTLD menu, the radio menu at any point in the menu tree causes the crash.

It seems like, not 100% but fairly sure, that the crash doesn't happen if the created group consists only of mortar units.

I've tried not allowing troops to search for enemy but it didn't make a difference (there are no enemy in the mission anyway).

Has this ever come up before with CTLD?  The issue could be in DCS or even my mission generator but I just wanted to see if it was a known issue.

**Comment by ciribob** [comment]
That sounds very odd... Never heard or seen that before!

Can you post a small sample & your DCS logs?

**Comment by emilianomolina** [comment]
Will do, I'll test with the newest CTLD and MIST first.

**Comment by emilianomolina** [comment]
The updated CTLD and MIST didn't help.  

I've attached the crash logs and the mission file.

[DCS crash logs.zip](https://github.com/ciribob/DCS-CTLD/files/638805/DCS.crash.logs.zip)
[Flight-0009 D03 TRNSPRT A to B 0900H 15C CLD1-10 AT5900 TO6900 WND10 FRM140 .miz.zip](https://github.com/ciribob/DCS-CTLD/files/638814/Flight-0009.D03.TRNSPRT.A.to.B.0900H.15C.CLD1-10.AT5900.TO6900.WND10.FRM140.miz.zip)

**Comment by ciribob** [comment]
tried replicating in the latest version but not seeing the crash... Maybe its fixed? I'll keep looking

**Comment by emilianomolina** [comment]
Did you try it with the attached mission? if so it may be a problem with my particular setup. 

Thanks for taking the time to look into this.

**Comment by ciribob** [comment]
I did but i'll try to test more soon! Its worth reporting that on the forum if you can replicate it in a very basic  mission.
