### ISSUE TITLE
Dcs 1.5 update 3 no CTLD option 

### ISSUE THREAD

**Issue by entropySG** [ciribob/DCS-CTLD#28]
CTLD not available in the F10 menu after today's dcs update, worked just fine before. Tried with clean mission no joy.
Oddly enough, when I take control of a ground unit that is named helicargo1 it works just fine but not in mi-8 or Huey

**Comment by jweisner** [comment]
Same problem here.

**Comment by ciribob** [comment]
Sorry for slow reply. Known bug, reported to ED and they're looking into it. Fingers crossed for a speedy fix!

**Comment by ciribob** [comment]
Fixed in latest 1.5 update 👍
