### ISSUE TITLE
I think the destroy crate, crash the server bug is back in 2.1.1

### ISSUE THREAD

**Issue by afinegan** [ciribob/DCS-CTLD#29]
I think the destroy crate, crash the server bug is back in 2.1.1.

I can sling load the crate (by rope), over to a spot, then when I deploy it, the whole server crashes.
`01392.274 INFO    SCRIPTING:   5266(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_HIT",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="SAMRADAR_NellisAFB12306964#001-06",},["TgtCategory"]=4,["IniUnitName"]="SAMRADAR_NellisAFB12306964#001-06",["TgtDCSUnit"]={["id_"]=399769612,},["TgtObjectCategory"]=5,["time"]=38969.515,["IniDCSGroup"]={["id_"]=1000547,},["target"]=,["initiator"]={["id_"]=17154817,},["WeaponName"]="5V55R",["IniDCSGroupName"]="SAMRADAR_NellisAFB12306964#001",["Weapon"]={["id_"]=17240577,},["IniDCSUnitName"]="SAMRADAR_NellisAFB12306964#001-06",["TgtUnit"]={["SceneryObject"]=,["ClassName"]="SCENERY",["SceneryName"]=399769612,},["IniCoalition"]=1,["id"]=2,["IniObjectCategory"]=1,["IniTypeName"]="S-300PS 40B6M tr",["IniCategory"]=2,["IniGroupName"]="SAMRADAR_NellisAFB12306964#001",["TgtDCSUnitName"]=399769612,["TgtUnitName"]=399769612,["TgtTypeName"]="WALL",["IniGroup"]={["GroupName"]="SAMRADAR_NellisAFB12306964#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnit"]=,["weapon"]=,},[3]="SAMRADAR_NellisAFB12306964#001-06",[4]=399769612,[5]=1,})
01392.274 INFO    Scripting: event:type=hit,weapon=5V55 S-300PS (SA-10B Grumble),initiator=SAMRADAR_NellisAFB12306964#001-06,target=WALL,t=38969.515,initiatorMissionID=1000553,targetMissionID=WALL,
01408.730 INFO    SCRIPTING:   5266(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_BIRTH",[2]={["initiator"]={["id_"]=17243393,},["id"]=15,["IniTypeName"]="1L13 EWR",["IniObjectCategory"]=1,["IniUnitName"]="Unpacked 1L13 EWR #168755152",["IniCategory"]=2,["IniCoalition"]=1,["time"]=0,["IniDCSGroup"]={["id_"]=1000984,},["IniDCSUnitName"]="Unpacked 1L13 EWR #168755152",["IniDCSUnit"]=,["IniDCSGroupName"]="_AI_1L13 EWR  #1582",},[3]="Unpacked 1L13 EWR #168755152",[5]=1,})
01408.730 INFO    SCRIPTING:   8382(  8755)/E:            DATABASE00003.AddGroup({[1]="Add GROUP:",[2]="_AI_1L13 EWR  #1582",})
01408.733 INFO    DCS: cargoCrashed:17240065
01408.745 INFO    SCRIPTING:   5266(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_DEAD",[2]={["id"]=8,["IniObjectCategory"]=6,["time"]=38985.715,["initiator"]={["id_"]=17240065,},},[5]=-1,})
01408.745 INFO    Scripting: event:type=dead,t=38985.715,initiatorMissionID=122092348,initiator=Early Warning Radar #122092348,`

**Comment by afinegan** [comment]
Sorry for the messy log post....

**Comment by ciribob** [comment]
Sorry meant to say I reported to ED

**Comment by afinegan** [comment]
Thanks man, I did 3 weeks ago, but they don't even acknowledge me.... Its VERY frustrating, especially from a professional coder. https://forums.eagle.ru/showthread.php?t=191090
