### ISSUE TITLE
Crash although I thought I have loaded Mist?

### ISSUE THREAD

**Issue by ST6Daniel** [ciribob/DCS-CTLD#32]
I crash it says mist not loaded, this is what I have set in Triggers though, what did I do wrong here? (Sry game is in german, I think I can't change to english other than reinstalling DCS?)
 
![mistcrash](https://user-images.githubusercontent.com/20766261/33607167-6f585f28-d9c0-11e7-81e6-2598fd874762.jpg)

**Comment by ciribob** [comment]
This is one for the forums really.... :)

Are you sure that you're loading CTLD after MIST? All I can see is a load of MIST and no CTLD

**Comment by ST6Daniel** [comment]
Ah alright. I am sure I loaded CTLD too :P
