### ISSUE TITLE
Cant get pickup-dropoff to work

### ISSUE THREAD

**Issue by Ironpond** [ciribob/DCS-CTLD#40]
I'm am super new to scripts. Anyhow, I was interested in this function shown in the pickup drop off demo, however it's not working. I loaded the demo, made no changes, and when I drop the extract10 team in the drop off they do not change to extract11... they just run off in some different direction then planned.

**Comment by ciribob** [comment]
This is an ED bug and has been reported. Sorry I  can't help anymore
