### ISSUE TITLE
FOB Deployment not showing FOB structure and watch tower.

### ISSUE THREAD

**Issue by carlwicker** [ciribob/DCS-CTLD#41]
FOB Deployment not showing FOB structure and watchtower.

Only shows a single mortar on deployment, fob functionality does work to deploy crates etc.

**Comment by ciribob** [comment]
DCS Bug unfortunately

**Comment by Ironwulf2000** [comment]
If you leave the server, and come back, it will be there. Similarly with crates that have been external sling loaded, they do not destroy. I believe this is a different issue however and has to do with the slinging script not terminating properly. The engine waits for the script to end, and when you leave the server, it obviously ends.
