### ISSUE TITLE
objects dropped on ships spawn underwater, ED bug or CTLD fix possible?

### ISSUE THREAD

**Issue by D4n2020** [ciribob/DCS-CTLD#51]
I heard on BlueFlag it's currently disabled cuz they spawn underwater. Does ED know about this, or can this even be fixed in CTLD?

**Comment by alcmann** [comment]
Any update on this ? was trying to spawn crates on the back of the Perry and LHA and still are spawning under the ship..

**Comment by ciribob** [comment]
DCS unfortunately
