### ISSUE TITLE
Diversify the jtac messages

### ISSUE THREAD

**Issue by FrancoFazz** [ciribob/DCS-CTLD#55]
Hi, I state that I am completely fasting of lua scripts. But I would like to ask. When you position a jtac, during the mission it starts to laser and sends a message on the screen with the coordinates and the rest. BUT in the presence of two different jtacs, it happens that the information that appears on the screen overlaps generating confusion for the pilots who are heading for different objectives. My question:
 Is it possible to display the message sent by the jtac only to the target that is interested in that particular goal? In this way it would be avoided that everyone sees the information of all the jtac which, if they appear together, is difficult to read.
I hope I explained myself correctly.
Thanks

**Comment by RexAttaque** [comment]
You can ask with JTAC special options a "9-Line" for each individual JTAC. There is also a better separator for when you reach the part of the status message for a new JTAC.
