### ISSUE TITLE
Is there a way to wildcard for LUA?

### ISSUE THREAD

**Issue by techdr1ve** [ciribob/DCS-CTLD#58]
In order to use CTLD and CSAR for DCS Liberation 2.0 Campaign, I must wildcard (MEDEVAC #1) for example. There is a bunch of information attached before and after. Is it possible for me to wildcard like this in LUA so that it works still? Any help would be greatly appreciated.

$MEDEVAC #1$

Currently, it's random and there isn't a quick and easy solution because of the random unit generation using pydcs.

**Comment by davidp57** [comment]
No need for this anymore, we've got type-based aircraft setup
