### ISSUE TITLE
Feature request: menu loading and hover pickup

### ISSUE THREAD

**Issue by LazyBoot** [ciribob/DCS-CTLD#69]
It could be nice if there was an option to have both menu loading of crates and hover pickup available at the same time. So that essentially the player could choose themselves how they want to load the crates.

**Comment by Queton1-1** [comment]
I've done that on my CTLD.
I sent modifications to Ciribob,

Details :
[1] add `ctld.loadCrateFromMenu = true`
[2] Replace this : ```if ctld.hoverPickup == false then```
By this : `if ctld.hoverPickup == false or ctld.loadCrateFromMenu == true then`
