### ISSUE TITLE
Feature Request: Sequence smoke color for autolase

### ISSUE THREAD

**Issue by CMGolden** [ciribob/DCS-CTLD#70]
It would be wonderful if each successive target lased by JTAC would be marked by a different color smoke marker and the text message identified the current target’s smoke color. Because smoke lasts for five minutes, sometimes there are many smoke marks and it is hard to tell the active target from the wrecked hulls already destroyed but still smoking. Colors could just sequence among all color options (or a specified set of color choices—even just alternating would help). Thanks!

**Comment by RexAttaque** [comment]
With the JTAC special options you can ask for a smoke on target. The color is always the same but at least you can reduce clutter this way.
