### ISSUE TITLE
Feature request: Imprecise smoke markers

### ISSUE THREAD

**Issue by magwo** [ciribob/DCS-CTLD#73]
It feels unrealistic that the target smoke markers are always _right_ on the marked vehicle.

I suspect immersion would be better if there was a randomized error added to the smoke marker position. For example +-50 meters on the lat/long of the smoke generator. This could perhaps be optional, perhaps not. Perhaps it should use normal distribution, perhaps not. 🤷 

I'm a contributor to Liberation and I think we would use this option for better realism and immersion, if it was available.

**Comment by magwo** [comment]
There's also the problem that the smoke sometimes obscures the vehicle, making it difficult to identify/confirm the vehicle type.

**Comment by robgrahamau** [comment]
this will allow for this, it gives a randomized +/- adjustment of up to 130 meters in each direction

`function ctld.createSmokeMarker(_enemyUnit, _colour)

    --recreate in 5 mins
    ctld.jtacSmokeMarks[_enemyUnit:getName()] = timer.getTime() + 300.0

    
    local _enemyPoint = _enemyUnit:getPoint()
    local xadjust = math.random(-130,130) -- Adjust randomly +/- 130 meters
	local zadjust = math.random(-130,130)
-- move smoke 2 meters above target for ease
    trigger.action.smoke({ x = (_enemyPoint.x + xadjust), y = _enemyPoint.y + 2.0, z = (_enemyPoint.z + zadjust) }, _colour)
end`

**Comment by robgrahamau** [comment]
if you want to make it optional / setable up the top you can even do this 
```lua
--add to the top options around lines 47 or so 
ctld.randomisedsmoke = true
ctld.maxrnddistance = 130
ctld.minrnddistance = -130

-- update this function
function ctld.createSmokeMarker(_enemyUnit,_colour)
    --recreate in 5 mins
    ctld.jtacSmokeMarks[_enemyUnit:getName()] = timer.getTime() + 300.0   
    local _enemyPoint = _enemyUnit:getPoint()
  xadjust = 0
  zadjust = 0
    if randomisedsmoke then
      xadjust = math.random(ctld.minrnddistance,ctld.maxrnddistance)
	zadjust = math.random(ctld.minrnddistance,ctld.maxrnddistance)
end
-- move smoke 2 meters above target for ease
    trigger.action.smoke({ x = (_enemyPoint.x + xadjust), y = _enemyPoint.y + 2.0, z = (_enemyPoint.z + zadjust) }, _colour)
end

```

**Comment by magwo** [comment]
@robgrahamau Is this a suggestion for a code change, or a way to do it yourself without changing the CLTD source code?

**Comment by robgrahamau** [comment]
> @robgrahamau Is this a suggestion for a code change, or a way to do it yourself without changing the CLTD source code?

Code change, you'd need to change the lines to get it to work.. I'd have suggested in a push to the repo for Ciri but atm i'm not at my normal machine

**Comment by davidp57** [comment]
Why not, good idea. I'll do this for the next release
