### ISSUE TITLE
Bug: Default JTAC code is 1112 -> invalid code, cannot set in F-14

### ISSUE THREAD

**Issue by fhoekstra** [ciribob/DCS-CTLD#74]
When picking up a JTAC from a pickup zone, then unloading them, they start lasing with code 1112.

This code is not a valid NATO laser code and cannot be set in DCS: F-14 kneeboard. Second digit must be 4 or higher, cannot be 1.

Is there a workaround to set a minimum or different default laser code for the first helo-deployed JTAC? I would like for the first deployed JTAC to be usable for F-14s too.

In the documentation, I only see the command to spawn a JTAC using a script, but I am talking about JTAC groups dropped by helicopters.

**Comment by ciribob** [comment]
https://github.com/ciribob/DCS-CTLD/blob/77b5f6008e0687470d34814fdd4f2b8b81bdf06b/CTLD.lua#L5866 

You can edit this function here

I used the A10C for the logic years ago so wasn't aware of the second digit rule

**Comment by fhoekstra** [comment]
Thanks for pointing that out, I will play around with it and submit a PR when I'm happy

**Comment by ciribob** [comment]
That would be great. Thanks!

**Comment by fhoekstra** [comment]
Fixed in #76
