### ISSUE TITLE
Patriot STR lacks 3 additional units for 360 coverage

### ISSUE THREAD

**Issue by NanoTrasen-Inc** [ciribob/DCS-CTLD#81]
A complete Patriot STR requires a minimum of 3 units facing independent directions in order to provide 360 degree coverage.
Currently the CTLD script only spawns 1 unit, meaning that contacts approaching from the other 2/3's of a circle will never be detected. This means the Patriot STR will rarely function correctly.

In order to solve this, logic would need to be added to spawn 3 STRs in a triangle, covering 3/3 directions.

See this image for clarification
![image](https://user-images.githubusercontent.com/1747249/194433994-29c0932d-f216-48fb-b00d-e92044e5ab0f.png)

**Comment by NanoTrasen-Inc** [comment]
Actually, I'm totally wrong on this. It needs 4 to achieve 360 degree coverage.
![image](https://user-images.githubusercontent.com/1747249/194434453-7dcc5a11-940e-47d8-845c-5f488d9aab0c.png)

**Comment by NanoTrasen-Inc** [comment]
Here is one with 3, just for reference
![image](https://user-images.githubusercontent.com/1747249/194434523-9c40e05b-48c6-4c17-90f0-2eb731ab6854.png)

**Comment by RexAttaque** [comment]
I've worked on some code to spawn an amount X of units of the same type and spawn them in a circle around their respective crate for AA systems, should solve this issue.

**Comment by davidp57** [comment]
@NanoTrasen-Inc can you please test the [upcoming 2024-11 release](https://github.com/ciribob/DCS-CTLD/pull/115) and tell if it fixes your issue?
