### ISSUE TITLE
Cant get new crates or troops from build fobs after latest DCS MT update

### ISSUE THREAD

**Issue by Xtrasher** [ciribob/DCS-CTLD#88]
Steps to Reproduce:
1. Join at Farp helicopter 
2. Take a FOB crate with CTLD F10 menu inside a pickzone
3. load crate internal or slingload
4. Drop crate somewhere
5. build FOB with CTLD F10 menu
6. try to get a new fob crate or troops at newly build farp 

get massage that there is no logistic zone nearby

**Comment by Fencer94** [comment]
Can confirm this existed until this patch, our rotary heads report FOBs working again as of 13th April, we did not alter anything in the CTLD script itself.

**Comment by ciribob** [comment]
This was due to the static bug which should (hopefully) be fixed now so I'll close for now
