### ISSUE TITLE
Empty JTAC status

### ISSUE THREAD

**Issue by karpiyon** [ciribob/DCS-CTLD#90]
Hi, 
I am running the JTACAutoLase, my drones lock on targets, smoke is show and I can lock on the designated targets.
However, the F10 JTAC status shows nothing.
Am I missing something?

**Comment by RexAttaque** [comment]
Are you in aircraft that is alone in it's group ? If I ask it in another way, how many aircrafts are in the mission editor group that your aircraft is part of ?

**Comment by davidp57** [comment]
Still no answer after almost a year; closing.
