### ISSUE TITLE
Can't load crates from ships?

### ISSUE THREAD

**Issue by ChaosRifle** [ciribob/DCS-CTLD#94]
I am struggling to get crate loading from boats to work at all. I have infantry working fine, but not crates. I do have logistics statics on the boat as well, though one would think that should be unnecessary.

UPDATE: looks like it is spawning them in the bottom of the ocean, and if the boat is moving, you can't pick them up once they are too far away.

perhaps make the script load it into the aircraft on spawn if pulled from a boat (if configured for internal loading), instead of trying to place it on a moving boat???

**Comment by davidp57** [comment]
Too complex, for such a small usecase.
If you can do it, please publish a PR and I'll consider adding it.

**Comment by ChaosRifle** [comment]
I do have a working prototype, I have used a normal logi supply unit (forklift) on the deck, but the crate is spawned in weird places at the bow of the boat, or on the deck grenading players. As of now, the play is to just instant load into the airframe, instead of slinging with or without ropes. life priorities changed though so unsure if I will ever get around to completing it, as direct loading wasnt working for me back then i did a hacky workaround to trigger the pickup function on deploy for testing purposes, which grenades things occasionally still. It does correctly move with the ship though, which was neat.
